- hosts: n2
  become: yes
  tasks:
    - name: Install Java and dependencies
      apt:
        name:
          - openjdk-11-jdk
          - wget
          - curl
        state: present

    - name: Add Jenkins repository
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
        echo "deb http://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
        apt update

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

