---
- name: Provision Jenkins Agents
  hosts: jenkins_agents  # Runs only on the Jenkins agents
  become: true
  vars_files:
    - vars.yml
  roles:
    - install_python
    - install_cron  # Ensure cron is installed before scheduling the script
    - schedule_script  # Moved setup_mysql out of here!

- name: Setup MySQL Server
  hosts: n4  # Runs only on the MySQL server
  become: true
  vars_files:
    - vars.yml
  roles:
    - setup_mysql
...