---
- name: Provision Jenkins Agents
  hosts: jenkins_agents  # Runs only on the Jenkins agents
  become: true
  vars_files:
    - vars.yml
  roles:
    - install_python
    - install_cron  # Ensure cron is installed before scheduling the script
    - schedule_script  # Moved setup_mysql out of here!

- name: Setup MySQL Server
  hosts: n4  # Runs only on the MySQL server
  become: true
  vars_files:
    - vars.yml
  roles:
    - setup_mysql

- name: Create MySQL Database  # This is the play name
  hosts: n4  # Specify which host should run this
  become: true
  vars_files:
    - vars.yml
  tasks:  # You need to have a tasks section
    - name: Create the database
      mysql_db:  # Now mysql_db is correctly placed as a module in a task
        name: system_stats
        state: present
        login_user: root
        login_password: team13@3
...