---
- name: Provision Jenkins Agents
  hosts: jenkins_agents
  become: true
  vars_files:
    - vars.yml
  roles:
    - install_python
    - install_cron
    - schedule_script

- name: Setup MySQL Server
  hosts: n4
  become: true
  vars_files:
    - vars.yml
  roles:
    - setup_mysql

- name: Database Operations
  hosts: n4
  become: true
  tasks:
    - name: Create MySQL database
      mysql_db:
        name: system_stats
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
...